# Generated by Django 4.2 on 2023-05-06 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_rename_description_task_ciudad_task_nombredecanato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('nombreParroco', models.TextField(blank=True)),
                ('ubicacion', models.TextField(blank=True)),
                ('horasanta', models.TextField(blank=True)),
                ('dia1', models.TextField(blank=True)),
                ('eucaristia', models.TextField(blank=True)),
                ('dia2', models.TextField(blank=True)),
                ('confesiones', models.TextField(blank=True)),
                ('dia3', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
