# Generated by Django 4.2 on 2023-05-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_parro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parro',
            name='horasanta',
            field=models.TimeField(blank=True),
        ),
    ]
