# Generated by Django 4.2 on 2023-05-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_notidi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notidi',
            name='user',
        ),
    ]
