# Generated by Django 4.2 on 2023-05-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_notidi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parro',
            name='horasanta',
            field=models.TextField(blank=True),
        ),
    ]
